### ISSUE TITLE
HW3 관련 질문입니다.

### ISSUE THREAD

**Issue by hyunseok0222** [snu-sf-class/pp201701#21]
HW 3의 3번 관련 질문입니다.

apply function이 의미하는 바가 정확히 무엇인가요?
제가 Test.scala 코드를 보고 이해한 바로는 Ty1과 Ty2의 틀이 주어졌을 때
주어진 a,b,c,d,e,f에 모두 값이 대입되는 함수인지요?

그리고 Test.scala에는 val r1, r2를 생성하고 있는데요
r1, r2가 단순히 Unit형이라고만 나오는데
r1, r2에 연관된 a,b,c,d,e,f 값 참조는 어떻게 해야 하나요?

**Comment by kim-yoonseung** [comment]
HW3의 두 번째인 apply 함수를 구현하는 방법에 관한 질문이지요?
우선 주석처럼 아래와 같이 코드를 바꾸시고:
`def apply(x: CommonTy, _a: A, _b: B, _c: C, _d: D, _e: E, _f: F) = x.apply(...)`

이제 ...에 들어갈 수 있는 값을 _a, _b, _c, _d, _e, _f 를 이용해 만들어내면 됩니다.
`CommonTy`를 올바르게 선언하셨다면 어떤 값이 들어가야 할 지 쉽게 알 수 있습니다.

또한 Test.scala 의 r1, r2를 풀어쓰면 다음과 같습니다.
```
val r1 = mc.apply(obj1, 0,0,0,0,0,0)
val r2 = mc.apply(obj2, 0,0,0,0,0,0)
```
mc.apply는 바로 위에서 구현한 apply 함수입니다. ???를 올바른 구현으로 채운 후에는 r1, r2가 Unit형이 아니라 위에서 구현한 apply가 리턴하는 타입의 값이 될 것입니다.

**Comment by hyunseok0222** [comment]
3번 문제 Syntax 관련하여 질문드립니다.

만약 함수가 {}에서 {val x : A; val y : B}
이라는 복합적인 값으로 대응되는 경우에는
Anonymous Function을 어떤 식으로 입력해야 하나요?

() => {A, B}
와 같이 쓰면  A, B를 value로 인식하여 에러가 발생합니다.

괄호를 ()=>(A,B)
로 바꾸어도 똑같이 에러가 발생합니다.

**Comment by kim-yoonseung** [comment]
structural type에 대한 함수도 특별히 어려울 것은 없는데요,
Int, String처럼 {}와 {val x:A; val y:B}도 타입이니까, 아래와 같이 하면 됩니다.
(x:Int) => "a" 라고 하면 Int => String 타입의 함수가 만들어지듯이, `(x:{}) => y` 라고 하고, y에 {val x:A; val y:B} 타입의 값을 넣으면 {} => {val x:A, val y:B} 의 함수가 만들어집니다.
만약 y의 위치에 즉석에서 record를 만들어서 사용하고 싶다면, 슬라이드에 나온 대로 `(x:{}) => new {val a = .. }` 와 같이 하면 됩니다.

특이한 사항은 new가 들어가는 것인데,

**Comment by hyunseok0222** [comment]
저런 식으로 함수 안에서 val을 정의하여
(y:{}) => new { val a : A ; val b : B }와 같이 코드를 작성하고 돌리니
Error:(31, 101) only classes can have declared but undefined members 에러가 발생하네요

그래서 A형의 값인 _a, B형의 값인 _b를 집어넣고 new를 없애서
((y:{}) => {_a ; _b })로 바꾸면

Error:(31, 79) type mismatch;
 found   : (AnyRef => B, C, E)
 required: AnyRef{val func: AnyRef => AnyRef{val a: A; val b: B}; val c: C; val e: E}

다음과 같이 Type A 를 인식하지 못하고 B, C, E만 출력됩니다.
어디가 잘못된걸까요ㅠㅠ

**Comment by HeeJaeLee12** [comment]
저도 위의 부분이 궁금함과 동시에,
비슷한 부분에서 계속 의문이 생기는데,
type Func1 = { val a: A } => { val b: B } // 이 부분이
{ val a: A } => { val b: B }의 결과 값의 type을 받겠다는 것인가요?
아니면 { val a: A } => { val b: B } 자체를 type으로 하겠다는 것인가요?

**Comment by bellatoris** [comment]
```scala
(y: {}) => new { val a: A = A type의 값, val b: B = B type의 값 }
``` 
로 하시면 컴파일 될거에요. `{ val a: A; val b: B }` type의 값을 return 해줘야 해서 new 로 선언해서 새로운 structural type의 value를 만들어야 하는데 `new { val a: A; val b: B }` 이렇게 하면 , `a`와 `b`가 선언은 되었지만 값이 할당 되지 않아서 오류가 나는 것 같습니다.

**Comment by kim-yoonseung** [comment]
@HeeJaeLee12 `type Func1 = { val a: A } => { val b: B }` 은 Func1이라는 타입의 이름을 정한 것입니다.
기본적으로 `type MyInt = Int` 와 다르지 않습니다.

@hyunseok0222 @bellatoris 님의 설명이 맞습니다. structural type과 그 타입의 값을 구분할 수 있어야 합니다.
`Int`가 타입, `3`이 그 타입의 값인 것처럼,
`{ val a :Int, val b:String}` 은 타입, `new { val a : Int = 3, val b : String = "aa"}` 는 그 타입의 값입니다.

**Comment by stjqkr** [comment]
CommonTy를 올바르게 작성하면 apply는 쉽게 알 수 있다고 하셨는데,
수퍼타입은 컴파일 에러 없이 잘 작성했는데도 apply에 뭘 써야 할지 전혀 감이 잡히지 않습니다.

하려는 것이 객체를 선언할 때(src/Test.scala) 선언하는 apply에 단순히 인자를 넘겨주는 것이 아닌지요?
그런데 syntax 구조에 제가 놓치고 있는 부분이 있는지, 계속 type mismatch, found : Unit 에러가 뜹니다.
또, src/Test.scala 안에서 함수를 x => new { ... } 로 입력하는데 여기서 x는 어디에 바인딩되어있나요?
x.apply()에 대해서 조금만 더 자세히 설명해 주시면 감사하겠습니다.

**Comment by kim-yoonseung** [comment]
apply 구현은 x.apply(..) 에서 ..에 들어갈 인자를 _a, _b, .. 등을 이용해 만들어내는 게 맞습니다.
에러가 뜬다면 뭔가 실수한 부분이 있을 것 같습니다.
그리고 x => new {.. } 에서의 x는 함수 parameter니까 매번 함수가 불릴 때마다 바인딩되는 값이 정해지겠죠.
mc(obj1, 0,0,0,0,0,0)을 부르면 내부적으로 obj1.apply( ... ) 가 될 거고, ... 안에 들어간 값이 x로 바인딩됩니다.
