### ISSUE TITLE
hw3 및 시험 때 사용할 에디터 관련 질문입니다. 

### ISSUE THREAD

**Issue by frmh0313** [snu-sf-class/pp201701#22]
3번 문제를 풀고 컴파일을 하면 

src/Main.scala:190: warning: reflective access of structural type member method apply should be enabled
by making the implicit value scala.language.reflectiveCalls visible.
This can be achieved by adding the import clause 'import scala.language.reflectiveCalls'
or by setting the compiler option -language:reflectiveCalls.
See the Scaladoc for value scala.language.reflectiveCalls for a discussion
why the feature should be explicitly enabled.

이런 메시지가 나오고, 에러메시지에 나온대로 import scala.language.reflectiveCalls를 하면 더이상 에러메시지가 출력되지 않는데 이 import 부분을 추가해도 괜찮나요? 아니면 이런 에러메시지가 나오지 않게 코드를 짜야하는 것인가요? 

그리고 에디터 관련해서 여쭤보고 싶은데, 시험과 관련된 공지사항에 아톰 에디터에 scala plugin이 설치되어 있기 때문에 도움이 될 거라고 하셨는데, ensime같은 플러그인이 설치가 된다는 것인가요 아니면 기본적으로 아톰 에디터의 기능으로 탑재가 되어 있다는 것인가요? 

감사합니다.

**Comment by kong0329** [comment]
저도 두번째 질문이 궁금합니다.
atom에 어떤 package가 설치되나요?
default Atom에서는 syntax highlight 같은 것이 되질 않는거 같습니다.

**Comment by kim-yoonseung** [comment]
@frmh0313 모범 답안은 특별히 다른 것을 import 하지 않아도 되는데, 어떻게 하셨는지 메일로 코드를 보내주실 수 있나요?

Atom 에디터는 https://atom.io/packages/language-scala 패키지를 시험장에 설치해달라고 요청하였고, 작년에는 시험 중에 잘 동작하였습니다. 빠른 시일 내에 제가 시험장 환경을 한 번 확인해보겠습니다.

**Comment by frmh0313** [comment]
@kim-yoonseung 조교님 안녕하세요. 답변 해주셔서 감사드립니다. 말씀하신 대로 코드는 메일로 보내드렸습니다. 감사합니다.

**Comment by kim-yoonseung** [comment]
제가 확인해보니 warning 인데, 이것은 import를 하셔도 좋고, 무시하고 그대로 제출하셔도 됩니다.
structural type을 가지는 object의 경우, new로 만들었거나 함수의 인자인 경우에는, "." 을 통해 내부 field를 접근하려고 하면 저 warning이 뜹니다.
수업 슬라이드에 있는 예제에서도 같은 warning이 뜨므로, 실행만 정상적으로 된다면 채점에는 문제가 없습니다.
