### ISSUE TITLE
HW3 3번 질문

### ISSUE THREAD

**Issue by yksnen11** [snu-sf-class/pp201701#25]
안녕하세요?
3번 문제를 풀긴 했는데, 아직 이해가 완벽하게 되지 않아서 출력 결과를 봐도 이게 된건지 잘 모르겠습니다. Test.scala에 있던 test code를 class 밑에 붙여넣기 한 결과, 다음과 같은 결과가 나옵니다. type match가 되고 있고 별다른 error가 없는 것 같은데, 원래 아래와 같이 나오는 건가요?

```
mc: MyClass[Int,Int,Int,Int,Int,Int] = MyClass@78dc5625

obj1: mc.Ty1 = $anon$3@11bf0754
obj2: mc.Ty2 = $anon$5@434a9f34

r1: AnyRef{val b: Int} = $anon$3$$anon$4@1390c1e1
r2: AnyRef{val b: Int} = $anon$5$$anon$6@e43b1ac

Test problem 3 by yourself
res0: Unit = ()
```

**Comment by kim-yoonseung** [comment]
컴파일이 잘 되었다면 아마 맞을 겁니다.

**Comment by yksnen11** [comment]
안녕하세요? 저는 컴퓨터공학부 이승현이라고 합니다. 답장주셔서 감사합니다.추가로 궁금한 점이.. 중간고사가 몇 문항으로 나오는 것인지 궁금합니다.(소문항개수) 그리고 혹시 오늘 출석확인을 했는지 여쭤보고 싶습니다.감사합니다.


삼성 갤럭시 스마트폰에서 보냈습니다.
-------- 원본 이메일 --------보낸 사람: kim-yoonseung <notifications@github.com> 날짜: 17/4/13  09:16  (GMT+09:00) 받은 사람: snu-sf-class/pp201701 <pp201701@noreply.github.com> 참조: yksnen11 <yksnen11@snu.ac.kr>, Author <author@noreply.github.com> 제목: Re: [snu-sf-class/pp201701] HW3 3번 질문 (#25) 
컴파일이 잘 되었다면 아마 맞을 겁니다.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/snu-sf-class/pp201701","title":"snu-sf-class/pp201701","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/snu-sf-class/pp201701"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kim-yoonseung in #25: 컴파일이 잘 되었다면 아마 맞을 겁니다."}],"action":{"name":"View Issue","url":"https://github.com/snu-sf-class/pp201701/issues/25#issuecomment-293742384"}}}
