### ISSUE TITLE
Website always says System Error (HW3)

### ISSUE THREAD

**Issue by taga5** [snu-sf-class/pp201701#26]
Everything works fine on my computer, all tests pass. But when I upload the hw3 to the website, it first says "RUNNING", and after a while it says "SYSTEM ERROR". I did not include any scripts, only src folder containing the .scala files.
What's the reason for this and how can I fix it?

**Comment by kim-yoonseung** [comment]
I fixed the grader several hours ago.
If you still see the problem, send me your zip file, then I will try to find the reason.
