### ISSUE TITLE
HW3 3번 Timeout

### ISSUE THREAD

**Issue by bekker** [snu-sf-class/pp201701#30]
HW3 3번에서 timeout으로 fail되었다고 나오는데, 틀린 건가요?
컴파일 오류 없이 CommonTy를 정의했고, r1.apply 결과도 제대로 출력하도록 코드를 작성하였습니다.

**Comment by kim-yoonseung** [comment]
혹시 지금도 그렇게 되어있다면 학번을 알려주시면 확인해보겠습니다. 메일로 알려주셔도 됩니다.

**Comment by bekker** [comment]
메일로 보내드렸습니다. 감사합니다.

**Comment by HeeJaeLee12** [comment]
저도 같은 상황이라 학번을 메일 드렸습니다.

**Comment by bekker** [comment]
#31
