### ISSUE TITLE
HW3 1번 질문입니다.

### ISSUE THREAD

**Issue by timedilation** [snu-sf-class/pp201701#35]
솔루션을 보면 deQ 함수의 경우
스택B에 원소가 있는 상태일경우 스택B에서 팝을 한다음 남은것을 다시 B에 위치하여 리턴하는데,
저는 구현할때 팝을 한 후 스택 A에 내용을 다시 옮겨서 리턴하도록 만들어서
스택 B는 항상 비어있게 구현하였습니다.
테스트중에 혹시 B스택에 내용이 있는채로 입력이 들어오거나 B스택을 검사하는 종류가 있었나요?
시험 직전에 여쭤봐서 죄송합니다.

**Comment by kim-yoonseung** [comment]
이걸 보실지 모르겠지만 스택 큐 기능만 잘 동작하면 내부는 임의로 구현하셔도 됩니다.
