### ISSUE TITLE
HW4 built-in type의 사용에 관한 질문

### ISSUE THREAD

**Issue by tjdans1114** [snu-sf-class/pp201701#36]
IterDict의 구현에 List 타입이 포함되는데, 그러면 List에 관한 method를 적절히 활용하는 것은 무방한가요?

그리고 IterDict.add는 append로 구현하는 건가요?

**Comment by kim-yoonseung** [comment]
List의 method를 사용하실 수 있습니다.
add의 구현은 자유롭게 하시면 됩니다. (append를 쓰셔도 되고 안 쓰셔도 됩니다.)
