### ISSUE TITLE
혹시 Midterm 성적 나왔나요?

### ISSUE THREAD

**Issue by kong0329** [snu-sf-class/pp201701#37]
안녕하세요. 

혹시 Midterm 성적이 나왔는지 여쭤봅니다.
숙제처럼 중간고사 사이트 들어가면 확인할 수 있나요?
그렇다면, 주소를 까먹었는데 알려주실수 있나요?

감사합니다.

**Comment by kim-yoonseung** [comment]
점수는 아직 안 나왔고, 나오면 확인할 수 있는 주소와 함께 공지하겠습니다.

**Comment by kong0329** [comment]
감사합니다
