### ISSUE TITLE
HW4에서 mutable variable 사용 가능한가요?

### ISSUE THREAD

**Issue by kong0329** [snu-sf-class/pp201701#38]
안녕하세요. 
혹시 HW4에서 mutable variable `var` 사용 가능한가요??

감사합니다.

**Comment by kim-yoonseung** [comment]
주석에 쓰인 대로, var과 같은 imperative feature를 사용하면 감점될 수 있습니다.

(https://www.scala-exercises.org/scala_tutorial/imperative_programming)

**Comment by kong0329** [comment]
감사합니다
