### ISSUE TITLE
implicitly[AddOp[Polynomial[Int]]].op(exp1, exp2) not working

### ISSUE THREAD

**Issue by stjqkr** [snu-sf-class/pp201701#57]
I've implemented everything for the Main.scala, well, hopefully. The basic code in Test.scala does fine. I then added **val addop: AddOp[Int]** and **val multop: MultOp[Int]** in order to test Polynomial types. It works perfectly with **Polynomial.eval(exp, intval)(multop, addop)**.

However, if I try to add or mult in the same way you did with Complex type, i.e. the title of this issue, It yields "**error: could not find implicit value for parameter e: pp201701.hw6.Data.DataBundle.AddOp[pp201701.hw6.Data.DataBundle.Polynomial[Int]]**".

I have **AddOps** and **MultOps** for both Polynomial[A] (required in Main.scala) and Int[A] (for my own unit test, in Test.scala). Is there anything I've missed to clarify to let scalac imply proper **AddOp** for **Implicitly[AddOp[Polynomial[Int]]]**?

**Comment by stjqkr** [comment]
My extended lines of Test.scala:

`  val addop = new AddOp[Int]{
    def op(a: Int, b: Int): Int = a + b
    val identity: Int = 0
    def inverse(a: Int): Int = -a
  }

  val multop = new MultOp[Int]{
    def op(a: Int, b: Int): Int = a * b
    val identity: Int = 1
  }

  val e1: Polynomial[Int] = List(1, 0, 3, 2)
  val e2: Polynomial[Int] = List(0, 1, 1)
  print_result(Polynomial.eval(e1, 1)(multop, addop) == 6) // this one's good

  val e = implicitly[MultOp[Polynomial[Int]]].op(e1, e2) // Here I've problem, same with AddOp, too.
  print_result(Polynomial.eval(e, 2)(multop, addop) == 174)`

**Comment by bellatoris** [comment]
Maybe you need to add `implicit` before 'val addop' and 'val multop'.
Like below

```scala
implicit val addop = ???
implicit val multop = ??? 
```

**Comment by stjqkr** [comment]
@bellatoris Problem solved. Thank you!
