### ISSUE TITLE
과제7 질문

### ISSUE THREAD

**Issue by yksnen11** [snu-sf-class/pp201701#59]
아래의 경우 어떻게 처리하면 되나요?
`pretty_printer(get_report(false, n))`에서
**A)** n이 음수일 때 어떤 메시지를 출력해야하나요? error: only positive input이라고 하면 되나요? 아니면 음수는 입력되지 않는다고 봐도 되나요?
**B)** n이 0일 때 <Pi 0>만 출력하면 되나요?

**Comment by Mistrie** [comment]
덧붙여서 질문이 있는데요, 
* (Test.scala대로) 1, 2를 포함한 모든 서수를 -th로 출력하면 되나요?

**Comment by kim-yoonseung** [comment]
- 음수는 입력하지 않을 것입니다.
- <Pi 0> 으로 출력하시면 됩니다.
- 모두 -th를 쓰시면 됩니다. 아니면 복잡해지니까요.
