### ISSUE TITLE
HW7 질문드립니다.

### ISSUE THREAD

**Issue by kong0329** [snu-sf-class/pp201701#60]
1. HW7에서 Data.scala파일을 보면 Dyn2 class도 정의되어 있는데,
이 class는 어디에 사용되는 건가요?

2. Report class가 abstract로 선언되어 있는데, 어떻게 처리해야 하는지 감을 잡지 못하겠습니다.
Report class를 구현을 해주어야지 문제를 풀 수 있나요?
만약 그렇다면, get_report method 내에서 따로 구현을 해주어야 하나요?

감사합니다.

**Comment by kim-yoonseung** [comment]
- Data.scala를 보시면 Iterable의 iter가 Dyn2 타입으로 되어있습니다. 슬라이드와 거의 같이 사용하시면 됩니다.
- 이번 숙제는 지금까지보다 좀 어려운데요, 힌트를 드리면 Report 클래스는 지금까지 배운 일반적인 타입클래스이므로 특별할 것 없이 지금까지 했던 대로 하면 됩니다. 구현 방법은 자유롭게 하시면 됩니다.
