### ISSUE TITLE
Readme 오타

### ISSUE THREAD

**Issue by bekker** [snu-sf-class/pp201701#63]
06/09: HW7 deadline postponed to 6/16(Thu) 23:59. For questions about HW7, visit TA in 14:00 ~ 16:00 of 6/14 (Wed), (Place: 301-416).

목요일이 아닌 금요일 같습니다.

**Comment by kim-yoonseung** [comment]
오타가 있었군요 감사합니다.
제출 기한은 14일 목요일입니다.
