### ISSUE TITLE
project due를 연장해주실 수는 없을까요

### ISSUE THREAD

**Issue by iwill231** [snu-sf-class/pp201701#75]
project due를 하루나 이틀 정도라도 연장해주실 수는 없을까요
기말 프로젝트들이 겹쳤는데 제대로 해서 내고 싶습니다.

**Comment by frmh0313** [comment]
저도 프로젝트가 겹쳤는데 이틀만이라도 연장해주시면 좋겠습니다.

**Comment by ss01363** [comment]
저도 겹쳐서... 지금 인턴 + 공연 준비 + 플젝 2개 하고 있는데 3일 내내 밤샘하고 오늘도 밤샘중입니다 ㅠㅠㅠ 내일 연차썼어요...

**Comment by gusdud1500** [comment]
플젝이 겹쳐서 시간이 너무 빠듯하네요.. 하루만이라도 연장 부탁드립니다 ㅜㅜ

**Comment by timedilation** [comment]
저도 비슷한 상황인데 연장해주시면 정말 감사하겠습니다ㅠㅠ

**Comment by kim-yoonseung** [comment]
일단 교수님께 말씀은 드려보겠습니다.

**Comment by shinjayne** [comment]
공감합니다 ㅠ
