### ISSUE TITLE
Can I get the solution code of the final project?

### ISSUE THREAD

**Issue by PluVian** [snu-sf-class/pp201701#80]
I implemented it, and it somewhat worked, but still it feels like OOP codes. I wonder how it can be solved in more functional way.

**Comment by kong0329** [comment]
저도 project code가 궁금합니다.
그리고 final exam solution도 궁금한데, 올려주시면 감사하겠습니다.

**Comment by kim-yoonseung** [comment]
I'll discuss this with professor first, and if we decide to post them here, we'll let you know. Thanks.

**Comment by PluVian** [comment]
Thanks for your help.
