### ISSUE TITLE
About HW score

### ISSUE THREAD

**Issue by kim-yoonseung** [snu-sf-class/pp201701#9]
Currently, the grading process of the server is not complete yet.
The score that will be uncovered (at the submission web page) after the deadline is not your actual score.
The actual score will be announced during this weekend.

**Comment by niyodav** [comment]
after several attempts to upload my assignment on he server, it has been running for more than 30 minutes and no results yet.
is there any thing that am doing wrong?

**Comment by kim-yoonseung** [comment]
@niyodav Let me know your student ID number. Before that, have you run Test.scala and checked everything's fine in the result? You should see four "O"s printed.

**Comment by niyodav** [comment]
@kim-yoonseung  i just fixed it sir! thanks and have a nice weekend

**Comment by optimisth** [comment]
<img width="546" alt="2017-03-25 6 05 02" src="https://cloud.githubusercontent.com/assets/17967652/24321023/9986b9ce-1185-11e7-8b39-4c12513e6bcd.png">

I entered git to check my score and it seems not working until now.

Are you still working on it?
